/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_loby_ffmpeg_android_FFmpegMedia */

#ifndef _Included_com_loby_ffmpeg_android_FFmpegMedia
#define _Included_com_loby_ffmpeg_android_FFmpegMedia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_loby_ffmpeg_android_FFmpegMedia
 * Method:    getFFmpegConfiguration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loby_ffmpeg_1android_FFmpegMedia_getFFmpegConfiguration
  (JNIEnv *, jclass);

/*
 * Class:     com_loby_ffmpeg_android_FFmpegMedia
 * Method:    watermarking
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_loby_ffmpeg_1android_FFmpegMedia_watermarking
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
